export const GET_API_TRENDING = "GET_API_TRENDING";
export const GET_API_TRAILERS = "GET_API_TRAILERS";
export const GET_LATEST_MOVIES = "GET_LATEST_MOVIES";
export const GET_SEARCH_MOVIES = "GET_SEARCH_MOVIES";
export const GET_ID_MOVIES = "GET_ID_MOVIES";
export const POST_TOKEN_LOGIN = "POST_TOKEN_LOGIN";
export const POST_SESSIONID_RESPONSE = "POST_SESSIONID_RESPONSE";
