export const GET_API_TRENDING = "GET_API_TRENDING";
export const GET_API_TRAILERS = "GET_API_TRAILERS";
export const GET_LATEST_MOVIES = "GET_LATEST_MOVIES";
export const GET_SEARCH_MOVIES = "GET_SEARCH_MOVIES";
